x-base-service: &base-service
    platform: ${DOCKER_IMG_PLATFORM:-linux/amd64}
    restart: "always"

services:
  allure:
    <<: *base-service
    image: frankescobar/allure-docker-service
    user: "${USER_UID}:${USER_GID}"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 10
      SECURITY_USER: ${SECURITY_USER}
      SECURITY_PASS: ${SECURITY_PASS}
      SECURITY_VIEWER_USER: ${SECURITY_VIEWER_USER}
      SECURITY_VIEWER_PASS: ${SECURITY_VIEWER_PASS}
      SECURITY_ENABLED: 1
    ports:
      - ${ALLURE_PORT}:5050
    volumes:
      - ./projects:/app/projects

  allure-ui:
    <<: *base-service
    image: frankescobar/allure-docker-service-ui
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "${ALLURE_HOST}:${ALLURE_PORT}"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - ${ALLURE_UI_PORT}:5252
